services:
  # 1. GATIMAN Backend API (Java Spring Boot)
  - type: web
    name: gatiman-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8088
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-da6025u417fc738t0mtg-a:5432/gatiman_db
      - key: DATABASE_USERNAME
        value: gatiman_user
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_ENABLED
        value: "true"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        value: mili241105@gmail.com
      - key: EMAIL_FROM_NAME
        value: GATIMAN Logistics
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  # 2. GATIMAN Frontend Web App (React Vite)
  - type: web
    name: gatiman-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    region: singapore
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://gatiman-backend.onrender.com/api
      - key: VITE_WS_URL
        value: https://gatiman-backend.onrender.com/ws
      - key: VITE_GOOGLE_CLIENT_ID
        value: 376704457217-hp4a0a55ot728nh2kk33pj6vp9projpl.apps.googleusercontent.com
      - key: VITE_RAZORPAY_KEY_ID
        value: rzp_test_TTNaA35CVbi6kG
