package com.gatiman.enums;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_CONFIRMED,
    AGENT_ASSIGNED,
    ORDER_PREPARING,
    ORDER_READY,
    PICKED_UP,
    IN_TRANSIT,
    OUT_FOR_DELIVERY,
    NEAR_DESTINATION,
    DELIVERED,
    DELIVERY_FAILED,
    DELIVERY_DELAYED,
    DELIVERY_CANCELLED,
    RESCHEDULE_REQUESTED,
    RESCHEDULE_APPROVED,
    RESCHEDULE_REJECTED,
    AGENT_REASSIGNED
}
